# Generated by Django 6.0.4 on 2026-04-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '商品收藏',
                'verbose_name_plural': '商品收藏',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='商品标题')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('image1', models.ImageField(upload_to='products/', verbose_name='图片1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='图片2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='图片3')),
                ('campus', models.CharField(max_length=100, verbose_name='校区')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='楼栋')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('active', '在售'), ('locked', '锁定中(预定)'), ('sold', '已售出'), ('removed', '已下架/违规')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
    ]
