# Generated by Django 6.0.4 on 2026-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='其他', max_length=50, verbose_name='分类'),
        ),
    ]
