# Generated by Django 6.0 on 2026-06-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_status_browsehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrowseHistory',
        ),
    ]
