# Generated by Django 6.0.4 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', '待付款'),
                    ('paid', '已付款'),
                    ('shipped', '已发货'),
                    ('arrived', '已到货'),
                    ('completed', '已完成'),
                    ('cancelled', '已取消'),
                    ('expired', '已过期'),
                ],
                default='pending',
                max_length=20,
                verbose_name='状态',
            ),
        ),
    ]
