# Generated by Django 6.0.4 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_add_arrived_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_name',
            field=models.CharField(max_length=100, null=True, blank=True, verbose_name='收件人姓名'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_phone',
            field=models.CharField(max_length=20, null=True, blank=True, verbose_name='收件人手机'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipping_address',
            field=models.CharField(max_length=255, null=True, blank=True, verbose_name='收货地址'),
        ),
    ]
