# Generated by Django 6.0.4 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(default='', max_length=20, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=100, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='00000000', max_length=8, verbose_name='学号'),
        ),
    ]
