# Generated by Django 6.0.4 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_user_grade_user_major_user_name_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='00000000', max_length=8, verbose_name='学号'),
        ),
    ]
