# Generated by Django 6.0.4 on 2026-04-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_grade_alter_user_major_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(error_messages={'unique': '该学号已被注册'}, max_length=8, unique=True, verbose_name='学号'),
        ),
    ]
