# Generated by Django 4.2.16 on 2026-05-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别'),
        ),
    ]
