# Generated by Django 6.0 on 2026-05-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
