# Generated by Django 6.0 on 2026-06-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
